// Emits the fixtures in shared/fixtures.ts as SQL, for seeding the hosted
// (D1) database with the same sample pedigrees the local `npm run db:seed`
// puts in birds.db — mainly so a freshly deployed Cloudflare instance has
// something real to look at (the cross-reference page in particular)
// without spending API credits on a first test upload.
//
// Writes to migrations/0002_seed_fixtures.sql. Re-run any time
// shared/fixtures.ts changes; uses INSERT OR REPLACE so re-applying is safe.
//
//   npm run db:seed:sql              # regenerate the .sql file
//   npm run db:seed:remote           # regenerate + apply to the live D1 db
//   npm run db:seed:local:d1         # regenerate + apply to local D1 (wrangler dev)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildFixtures } from '../shared/fixtures.js';
import type { Bird } from '../shared/types.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = path.resolve(__dirname, '..', 'migrations', '0002_seed_fixtures.sql');

function sqlValue(v: string | number | boolean | null | undefined): string {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? '1' : '0';
  return `'${v.replace(/'/g, "''")}'`;
}

function birdInsert(b: Bird): string {
  const cols = [
    'id',
    'ring',
    'ring_normalised',
    'name',
    'colour',
    'sex',
    'breeder',
    'loft_address',
    'notes_json',
    'notes_en_json',
    'results_json',
    'sire_id',
    'dam_id',
    'source_file',
    'confidence',
    'verified',
  ];
  const values = [
    b.id,
    b.ring,
    b.ringNormalised ?? null,
    b.name ?? null,
    b.colour ?? null,
    b.sex,
    b.breeder ?? null,
    b.loftAddress ?? null,
    JSON.stringify(b.notes ?? []),
    b.notesEn ? JSON.stringify(b.notesEn) : null,
    JSON.stringify(b.results ?? []),
    b.sireId ?? null,
    b.damId ?? null,
    b.sourceFile ?? null,
    b.confidence,
    b.verified,
  ];
  return `INSERT OR REPLACE INTO birds (${cols.join(', ')}) VALUES (${values.map(sqlValue).join(', ')});`;
}

function main() {
  const { birds, uploads, childPedigrees } = buildFixtures();

  const lines: string[] = [
    '-- Auto-generated by scripts/build-seed-sql.ts from shared/fixtures.ts. Do not hand-edit.',
    '-- Regenerate with: npm run db:seed:sql',
    '',
    '-- birds (already in parent-before-child order, satisfying sire_id/dam_id foreign keys)',
  ];
  for (const b of birds) lines.push(birdInsert(b));

  lines.push('', '-- uploads (one row per parent-side pedigree, all pre-verified sample data)');
  for (const u of uploads) {
    lines.push(
      `INSERT OR REPLACE INTO uploads (id, original_filename, stored_path, root_bird_id, verified) VALUES (${[
        u.id,
        u.originalFilename,
        u.storedPath,
        u.rootBirdId,
        true,
      ]
        .map(sqlValue)
        .join(', ')});`,
    );
  }

  lines.push('', '-- child_pedigrees');
  for (const cp of childPedigrees) {
    lines.push(
      `INSERT OR REPLACE INTO child_pedigrees (id, child_bird_id, sire_upload_id, dam_upload_id, prose_json) VALUES (${[
        cp.id,
        cp.childBirdId,
        cp.sireUploadId,
        cp.damUploadId,
        JSON.stringify(cp.prose),
      ]
        .map(sqlValue)
        .join(', ')});`,
    );
  }

  fs.writeFileSync(OUT_PATH, lines.join('\n') + '\n', 'utf-8');
  console.log(`Wrote ${birds.length} birds, ${uploads.length} uploads, ${childPedigrees.length} child pedigrees to ${OUT_PATH}`);
}

main();
